UD_VERSION = "2.6"
UD_TREEBANKS_DIR = f"ud-treebanks-v{UD_VERSION}"
SUD_TREEBANKS_DIR = f"sud-treebanks-v{UD_VERSION}"

# TREEBANK FILTERING
RATING_THRESHOLD = 0.7
TOKENS_LOWER_THRESHOLD = 70000
TOKENS_UPPER_THRESHOLD = 1000000

# EMBEDDING PRUNING
WORD_VECTORS_N = 300000

CUDA_DEVICE = False

# DRY RUN MODE
DRY_RUN = True
DRY_SENT_NUM = 100

